### ISSUE TITLE
network ipvlan configuration

### ISSUE THREAD

**Issue by ognetravco** [PubSec-Security-DevNet/iPSK-Manager-Docker#1]
The original project was great but running it as a docker just makes more sense.

I am only assuming some users won't know that you can apply an ipvlan interface to the docker to give them different configuration options, like a static IP. Would be awesome to provide an example in the config guide. Below is an example of what i used.

```
docker network create -d ipvlan --subnet=192.168.10.0/24 \
--gateway=192.168.10.1 -o ipvlan_mode=l2 -o parent={{docker host physical interface}} ipvlan{{vlan number, like 100}}

docker build -t ipskmanager-image . --build-arg SQL_PASSWORD=1234 --no-cache

docker run -d --name ipskmanager --mount source=mysqldata,destination=/var/lib/mysql \
--mount source=ipskconfig,destination=/opt/ipsk-manager \
--net=ipvlan100 --ip=192.168.10.100 \
ipskmanager-image
```

**Comment by ciesinsn** [comment]
Thanks for the feedback I'll add this to the README
