### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by ognetravco** [PubSec-Security-DevNet/iPSK-Manager-Docker#2]
I've been trying to get email notification to work with no luck. Looking at the source, it looks like the emails only work when endpoints are created. Is this a sponsor portal feature only? It would be great if it work for non-sponsor and when the endpoint is close to or hits the expiration point so it can be extended.

I did try making the following PHP script on the container an running over the GUI and CLI with no luck. 
The CLI says /usr/sbin/sendmail : not found

https://conetix.com.au/support/simple-php-mail-test/

**Comment by ciesinsn** [comment]
I have not updated the documentation for the docker container project yet, but, I noticed the original author of iPSK Manager wasn't actually using a SMTP server even though the config items are there.  I recently pushed a update to iPSK Manager to actually support a SMTP server so if you rebuild your image where it pulls the latest iPSK Manager you should be able to use a SMTP server for emails. 

The existing iPSK Manager code was using the built in MTA sender of the OS and the Docker container in this project doesn't have sendmail installed.

**Comment by ciesinsn** [comment]
As for when it emails its when a endpoint is created and the credentials are emailed to user.  If you want to see more email functionally can you post a issue to the iPSK Manager main project and I can see what it would take to add.

**Comment by ognetravco** [comment]
Thank you for the feedback. I just did a 'git fetch' and rebuild the docker image but now I'm getting an error when creating a new endpoint. I did blow away the docker volumes and recreated everything and the problem persist. You already answer my original question so not sure if I should open another issue for this.

**Comment by ognetravco** [comment]
Forgot to put the error.

`Error Loading Selection: Verify the installation/configuration and/or contact your system administrator!`

**Comment by ciesinsn** [comment]
In the latest iPSK Manager update there is a schema change on a few tables.  A existing deployment should get a prompt when logging into the admin portal that a schema change is needed and the README of the Docker project has documentation on how to do that update on a existing deployment. 

If you completely removed the old mysql database and started from scratch the new install should have made the tables with the new fields.  

The error you mention where is that seen?  Can you attach a screenshot?

**Comment by ognetravco** [comment]
I did notice the schema update notice and applied the commands. I figured I did something wrong so decided to start with a fresh install. Below is the error as it shows up on the admin portal and regular non-sponsor portal. On the non-sponsor portal, the page just looks white so i focused on the debug console to display the error.

![image](https://github.com/PubSec-Security-DevNet/iPSK-Manager-Docker/assets/50750315/5f82d725-554b-46da-ab68-951a78c42b69)


![image](https://github.com/PubSec-Security-DevNet/iPSK-Manager-Docker/assets/50750315/98a28e3c-6377-4b5e-ba26-b87173824334)

**Comment by ognetravco** [comment]
Maybe this part of the debug will be more helpful.

![image](https://github.com/PubSec-Security-DevNet/iPSK-Manager-Docker/assets/50750315/897e5860-7dd0-4de9-99b0-aae8376aadb8)

**Comment by ciesinsn** [comment]
I wouldn't rule out me doing something wrong either, ha.   Are you able to connect to your mysql DB and get the current schema for your endpoint table?

**Comment by ciesinsn** [comment]
I also see its a 500 server error, did apache put anything in the docker logs?

**Comment by ognetravco** [comment]
The endpoint table is blank but this error looks promising. This capture is from trying to add an endpoint from the admin portal.

`[Thu Jun 20 18:30:59.027148 2024] [php:error] [pid 340] [client 10.251.152.64:53731] PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'lastUpdated' doesn't have a default value in /var/www/iPSK-Manager/supportfiles/include/iPSKManagerDatabase.php:1862\nStack trace:\n#0 /var/www/iPSK-Manager/supportfiles/include/iPSKManagerDatabase.php(1862): mysqli->query()\n#1 /var/www/iPSK-Manager/supportfiles/adminportals/modules/endpoints/create.inc.php(78): iPSKManagerDatabase->addEndpoint()\n#2 /var/www/iPSK-Manager/adminportal/ajax/getmodule.php(73): include('...')\n#3 {main}\n  thrown in /var/www/iPSK-Manager/supportfiles/include/iPSKManagerDatabase.php on line 1862, referer: https://ipsk-manager.test.local:8443/adminportal.php
192.168.1.10 - - [20/Jun/2024:18:30:59 +0000] "POST /ajax/getmodule.php HTTP/1.1" 500 3548 "https://ipsk-manager.test.local:8443/adminportal.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0"`

**Comment by ciesinsn** [comment]
What I kind of thought it may be.  Let me see if I can reproduce and do a fix quick.

**Comment by ciesinsn** [comment]
So the weird thing is I can reproduce the issue within my docker container, but, I can't when its running outside the container and both mysql DB's have the same schema.  I did though make a change to the schema setup and pushed it up to the iPSK Manager repository so a fresh build of iPSK Manager on Docker should work fine now.  If you wanted to modify your current installed instance without having to rebuild.

1) Connect to the Docker container shell
2) Run `mysql`
3) Type `use ipsk`
4) Type `ALTER TABLE endpoints MODIFY COLUMN lastUpdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;`

**Comment by ognetravco** [comment]
I applied the change and it resolved the issue. I can create endpoint entries and I can see SMTP traffic but I'm not getting the email. But I think my internal security has something to do with that.

I appreciate the quick fix to this.

**Comment by ognetravco** [comment]
Finally received an email alert. My email gateway was set to port 25 but it also allowed encryption. The iPSK Manager email client was trying to switch over to TLS, even when configure to encryption "none." Changing this to "STARTTLS" allow the email to finally be delivered.
